version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    container_name: hello-doctor
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - "80:80"

  hello-doctor.database:
    image: postgres:latest
    restart: always
    container_name: hello-doctor.database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin@123
      - POSTGRES_DB=hello_doctor_db
    volumes:
      - ./.containers/hello-doctor-db:/var/lib/postgresql/data

  
  # nhume.cache:
  #   image: redis:latest
  #   container_name: nhumeapi.cache
  #   restart: always
  #   ports:
  #     - "6379:6379"
