version: '3.4'

services:
  hellodoctor.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "8080:8080"
      - "5001:5001"
    volumes:
      - ~/.microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/Https:/home/app/.aspnet/https:ro
      - ./.containers/logs:/logs