version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    container_name: hello-doctor
    build:
      context: .
      target: final
      dockerfile: src/Web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      hello-doctor.database:
        condition: service_healthy

  hello-doctor.database:
    image: postgres:latest
    restart: always
    user: postgres
    container_name: hello-doctor.database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin@123
      - POSTGRES_DB=hello_doctor_db
    volumes:
      - ./.containers/hello-doctor-db:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD", "pg_isready" ]
        interval: 10s
        timeout: 5s
        retries: 5

  
  # nhume.cache:
  #   image: redis:latest
  #   container_name: nhumeapi.cache
  #   restart: always
  #   ports:
  #     - "6379:6379"
