# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  hellodoctor.api:
    build:
      context: "/Users/comfort/Projects/hello-doctor-api"
      dockerfile: "src/Web/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/ApiBaseTemplate.Web.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "hellodoctorapi:dev"
    ports:
    - "127.0.0.1:57005:57100"
    - "127.0.0.1:57205:57300"
    volumes:
    - "/Users/comfort/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/comfort/Projects/hello-doctor-api/src/Web:/app:rw"
    - "/Users/comfort/Projects/hello-doctor-api:/src:rw"
    - "/Users/comfort/.local/share/JetBrains/RiderRemoteDebugger/2024.1.4/LinuxArm64:/opt/rider-debugger"
    - "/Users/comfort/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/comfort/Library/Logs/JetBrains/Rider2024.1/DebuggerWorker/JetBrains.Debugger.Worker.2024_7_20_23_13_47:/var/opt/rider-debugger:rw"
    working_dir: "/app"
